### ISSUE TITLE
Implement Page Designs from Figma

### ISSUE THREAD

**Issue by kajchang** [petcodeapp/interface-web#13]
- Login / Registration
  - [x] Login
  - [x] Registration
  - [x] Forgot Password

- Landing
  - [x] Landing

- Account
  - [x] Dashboard
  - [x] Contact Info
  - [x] Pet Info
  - [x] Medical Info
  - [x] Scan Locations

- Store
  - [x] Shop Page
  - [x] Single Product Page
  - [x] Shipping Info
  - [x] Billing Info
  - [x] Review & Confirmation

- Public
  - [x] Pet Profile

- Misc.
  - [x] Contact Us
  - [ ] Privacy Policy
  - [ ] Terms and Conditions
  - [ ] Help Center

**Comment by rishiosaur** [comment]
@kajchang Updates on this?
